"""add 

Revision ID: 00022851a8bc
Revises: 3d07eeaa8f63
Create Date: 2025-07-21 16:04:19.215137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00022851a8bc'
down_revision: Union[str, Sequence[str], None] = '3d07eeaa8f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_requests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_requests', 'updated_at')
    # ### end Alembic commands ###
