"""Add OptimizationResult table

Revision ID: 54bd58516772
Revises: 6cee88d09cd9
Create Date: 2025-07-26 16:22:54.402921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54bd58516772'
down_revision: Union[str, Sequence[str], None] = '6cee88d09cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_requests', 'dataset_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('optimization_results', 'best_parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('optimization_results', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('optimization_results', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('optimization_results', 'best_parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('data_requests', 'dataset_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
