"""add_role_to_user_profile

Revision ID: 8fb50e8259e4
Revises: 566d96e716f4
Create Date: 2025-08-11 16:45:59.476171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb50e8259e4'
down_revision: Union[str, Sequence[str], None] = '566d96e716f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajouter d'abord la colonne comme nullable
    op.add_column('user_profiles', sa.Column('role', sa.String(), nullable=True))
    
    # Mettre à jour tous les enregistrements existants avec la valeur par défaut 'user'
    op.execute("UPDATE user_profiles SET role = 'user' WHERE role IS NULL")
    
    # Maintenant rendre la colonne NOT NULL
    op.alter_column('user_profiles', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'role')
    # ### end Alembic commands ###
